version: '3'

tasks:

  BaseBuildAllCodeunits:
    desc: "Base: Build all codeunits"
    silent: true
    dir: "."
    cmds:
      - scbuildcodeunits
    aliases:
      - basebuildallcodeunits
      - bb

  GryvapaperserverRunExample:
    desc: "GRYVAPaperServer: Run example"
    silent: true
    dir: "."
    cmds:
      - python GRYVAPaperServer/Other/Reference/ReferenceContent/Examples/MinimalDockerComposeFile/RunExample.py
    aliases:
      - gryvapaperserverrunexample
